language: android
dist: trusty
jdk:
  - oraclejdk8

rvm:
  - 2.2
android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - extra

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - $HOME/.rvm/

before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-30"
  - chmod +x ./run_calabash.sh

install:
  - gem update --system
  - rm -f -r ruby26\lib\ruby\gems\2.4.0\specifications\default
  - yes | gem uninstall calabash-android
  - yes | gem uninstall json
  - gem install bundler
  - bundle install

addons:
  sonarcloud:
    organization: "ziyao987"
    token:
      secure: "fEwgpyPApnx/r8+U5icCa5+Rz6j1ManAvODEvlvwjNp8ILW0mT1EQX4K2km/mXWoWF39+pIURzbCNyBRxr07pI0+amGSbWY5AhQj98av9oPt5rtnCKDCdW8rk04MmnpdR4NJzEvVJNr1i2v0IwPVsBd+ZsDnJxfZ/ThT40rqbn5tadTPNOnqSX9Ltd5lRAi4ia5oQ6n
PAYdvUvT8CPEcfKBRZZIJbUgGTrSWVKbDVabgXe4a2a6H7PHYFvk0qPn7tQUzJlHtvfClA5sirY2pMsTjRvWlyMHpIRjZmW/SmfXffszyeGRPuOziP0hFdGBFItpMeVYbxmJ46Z3INKTNBwSdeJiEupR0ImVwxDNYduuHUrh5kyau1BKCkfS6Pl98CaWCFDp9Coyt0O0qvDJjP8byz
Q/dYKHIjKCUjL0Doux5LYfaWzHG+Sn081dnL7HntuhIaOvtNolInJnAKnZ2MqttZcDuBfdBIuM+qTlllFzAZPK4kzTAzkoM4FqCHCf82U7n3S01EG0rn9d4Uo4RYrrABBujCkL57uTYI54D6FDB0bO6ZAbfvnhTO/LM/qapL0Tyvb6jxd9+hKUk7Gp1nG5REdIHc53h5cqet2k3x+i
fptHlhjCuy/0dgkXLTsZ/u07AEjuvp7Bz5vcUqzFQqePreqDf9rI7H/PcfqIPb4I=" # encrypted value of your token


script:
  - ./gradlew build
  - ./run_calabash.sh
